version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - php

  php:
    image: php:8.1-fpm-alpine
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend
    depends_on:
      - mysql

networks:
  frontend:
  backend:

volumes:
  mysql_data: